# Generated by Django 4.2.2 on 2023-06-16 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_signup_date_like_updated_at_post_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='geolocation',
            new_name='location',
        ),
    ]
